version: "3.3"

services:
    server:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 8000:8080
        volumes:
            - ./app:/go/src/app
            - ./public:/go/src/public