 
FROM golang:1.16 as build

WORKDIR /go/src
COPY . .

ENV PATH="/go/bin:${PATH}"

RUN GOOS=linux go build -o . app/main.go


FROM golang:1.16

WORKDIR /go/app

COPY ./public ./public

COPY --from=build ./go/src/main .

EXPOSE 8080

CMD ["./main"]